title: Blogger Foo
email: bloggerfoobar@yahoo.com
description: >- # this means to ignore newlines until "baseurl:"
  I am Foo. This is my blogging platform. Programmers use me as a
  placeholder name in their Computer programs to name entities such as
  Variables, Functions, Commands etc to demonstrate more concept
  than the identity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
future: true # Show blog post of future date

google_analytics: foo-bar-google-analytics-id # Replace it with your ID starting as UA-

paginate: 6
paginate_path: "/blogs/page:num"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-paginate
